# These settings are synced to GitHub by https://probot.github.io/apps/settings/

# Labels: define labels for Issues and Pull Requests
labels:

  - name: 1 SP
    color: '#FFFFFF'
    description: 1 story point

  - name: 2 SP
    color: '#FFFFFF'
    description: 2 story points

  - name: 3 SP
    color: '#FFFFFF'
    description: 3 story points

  - name: 5 SP
    color: '#FFFFFF'
    description: 5 story points

  - name: 8 SP
    color: '#FFFFFF'
    description: 8 story points

  - name: bug
    color: '#d73a4a'
    description: Something isn't working.

  - name: enhancement
    color: '#0E8A16'
    description: An enhancement or an additional functionality.

  - name: feature
    color: '#0E8A16'
    description: A feature or new functionality.

  - name: maintenance
    color: '#1D76DB'
    description: Maintenance of code base and other fundamentals.

  - name: needs refinement
    color: '#000000'
    description: Don't start working on this, this issue needs a task refinement.
    
  - name: major
    color: '#d9d9d9'
    description: Major version change, there are incompatible API changes.

  - name: minor
    color: '#d9d9d9'
    description: Minor version change, there is new and extended functionality in a backwards compatible manner.

  - name: patch
    color: '#d9d9d9'
    description: Patch version change, there are changes, enhancements and fixes which are backwards compatible.
    
