name: Release Drafter
# for further info see: https://github.com/release-drafter/release-drafter#readme

on:
  push:
    branches:
      - main
    
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-18.04
    steps:
      # Drafts the next release notes as pull requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/
        with:
           config-name: release-drafter-config.yml
        #  disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
